name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  calendar_day_view:
    path: ../
  cupertino_icons: ^1.0.2
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  intl: ^0.17.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
